//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTResourceMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RTResourceMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   // vars
        ///$game_textbtn_def_unsel_hex:#000000
        ///$game_textbtn_def_unsel_alpha:255
        ///$game_textbtn_def_sel_hex:#808080
        ///$game_textbtn_def_sel_alpha:255
        ///$game_title_def_hex:#000000
        ///$game_title_def_alpha:255
        ///
        ///// main
        ///main.sidebar.hex=#FFFFFF
        ///main.sidebar.alpha=70
        ///main.rectangle.hex=#FFFFFF
        ///main.rectangle.alpha=70
        ///
        ///main.menu.gamestart.unsel.hex=#FFFFFF
        ///main.menu.gamestart.unsel.alpha=255
        ///main.menu.gamestart.sel.hex=#808080
        ///main.menu.gamestart.sel.alpha=255
        ///
        ///main.menu.setting.unsel.hex=#FFFFFF
        ///main.[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string data_color_dat {
            get {
                return ResourceManager.GetString("data_color_dat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   atus_white.png
        ///rt_logo.png
        ///routeadd_shadow.png
        ///rt_icon_img.png
        ///rt_icon_ico.ico과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string images_hides {
            get {
                return ResourceManager.GetString("images_hides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap music_file {
            get {
                object obj = ResourceManager.GetObject("music_file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap rtrmlogo {
            get {
                object obj = ResourceManager.GetObject("rtrmlogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   hamjung.wav과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string sounds_hides {
            get {
                return ResourceManager.GetString("sounds_hides", resourceCulture);
            }
        }
    }
}
